[package]
edition = "2021"
name = "stockcode-parser"
version = "0.1.0"

[dependencies]
nom = "7"
peg = "0.8.1"
pest = "2.5.5"
pest_derive = "2.5.5"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
harness = false
name = "bench"
