name: CI
on: [push]
jobs:
  test_rust:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup | Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ubuntu-test-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: cargo test
  test_go:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup | Cache Go
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod/
          key: ubuntu-test-go-${{ hashFiles('**/go.sum') }}
      - name: Test
        run: go test ./...
